<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EventDrivenShop.Contracts\EventDrivenShop.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventDrivenShop.Common\EventDrivenShop.Common.csproj" />
    <ProjectReference Include="..\EventDrivenShop.OrderService.Domain\EventDrivenShop.OrderService.Domain.csproj" />
  </ItemGroup>

</Project>
