<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.2" />
    <PackageReference Include="MassTransit.TestFramework" Version="8.3.6" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.3.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\EventDrivenShop.Contracts\EventDrivenShop.Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\EventDrivenShop.Common\EventDrivenShop.Common.csproj" />
    <ProjectReference Include="..\..\src\Services\Orders\EventDrivenShop.OrderService.Api\EventDrivenShop.OrderService.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Payments\EventDrivenShop.PaymentService.Api\EventDrivenShop.PaymentService.Api.csproj" />
    <ProjectReference Include="..\..\src\Services\Notifications\EventDrivenShop.NotificationService.Api\EventDrivenShop.NotificationService.Api.csproj" />
  </ItemGroup>

</Project>
